#include "Zombie.hpp"

#define NAMES {"CANAS", "PERNA", "DARE", "STRUCK", "NAY", "SEVERINO", "BOULDIN", "MATHEWSON", "TOPETE", "BRUNETTE", "SIN", "ALESSI", "BRICKEY", "FERRIER", "HENDREN", "SCHEEL", "STORER", "HIBBERT", "KLINGENSMITH", "MATHERNE", "MECHAM", "SPIKER", "BANKHEAD", "BANNING", "LEFEVER", "ROAN", "BRACK", "DAVIE", "PASCOE", "SCHEID", "JIM", "REVIS", "STRAHAN", "TWEEDY", "FERMIN", "MOTES", "OBRIAN", "LOBO", "PALMISANO", "BYINGTON", "FAUGHT", "GARREN", "HUNGERFORD", "VANZANDT", "GUST", "HEATER", "DELAY", "KLINGLER", "GAUGHAN", "HENDLEY", "THREATT", "WEAR", "KUNZE", "HESSLER", "LINDELL", "MONTELEONE", "PALAZZOLO", "CAVALIER", "PHARES", "SHEAR", "BENNING", "URBANSKI", "DARRAH", "MOHN", "VEREEN", "WAGER", "BEILER", "HEDLUND", "QUADE", "WIECZOREK", "CICERO", "DUCOTE", "HOEKSTRA", "SCALF", "HAVARD", "BEACHAM", "ESPIRITU", "BOLGER", "DICE", "LEMMONS", "SCHULLER", "SILL", "ORLOWSKI", "LAINE", "LUNDEEN", "RAKES", "STANFILL", "STECK", "DURRETT", "HAVILAND", "NAUMANN", "AMOROSO", "DONAHOE", "FRANCK", "REIF", "BELKNAP", "PERROTTA", "TOLLE", "DOUGAN", "HEYER", "FRAKES", "LEATH", "POTEAT", "GRANILLO", "MARINE", "VIOLETTE", "ZELLNER", "DIDONATO", "FONTANEZ", "BRADBERRY", "MORMAN", "MENTZER", "LAMOUREUX", "CATANIA", "SABATINO", "WENNER", "ANTONUCCI", "HEPBURN", "LOSEY", "PASTRANA", "SHENK", "EGGER", "HIGBEE", "ADAMES", "REEP", "CAVALLO", "BRIDWELL", "EVERETTE", "PEET", "POOR", "VILLALBA", "ARNEY", "MARROW", "SHARON", "TOWERY", "TRAINER", "CUMMING", "RIMMER", "FELT", "GARRARD", "PARRETT", "PINTER", "STANGER", "BENEDETTO", "LINGENFELTER", "BILLY", "RESCH", "CALDERONE", "MIKESELL", "OSTERMAN", "REDFERN", "TRUEBLOOD", "PLACENCIA", "VARNADO", "WAMSLEY", "WARR", "HARSHBARGER", "TOPPING", "DECOSTA", "FELTNER", "TART", "BLUMBERG", "CULLEY", "SHAIKH", "BORK", "THIBEAULT", "STOLZ", "RAMSDELL", "TEDFORD", "DAVES", "NOTO", "POULSON", "ALTIERI", "GRAFTON", "HARTLINE", "KISNER", "MENDOSA", "REMY", "ANSARI", "CRIPE", "HARTFIELD", "MULVANEY", "SHER", "WATHEN", "WHITTON", "EISELE", "HINOJOS", "BACKER", "SCHUETZ", "SPEAKS", "MARCOS", "MASK", "NOVOA", "OBOYLE", "KIRCHER", "STANG", "SCALA", "SIBERT", "HALVORSEN", "HENDON", "MONTALBANO", "ZACARIAS", "ZERMENO", "BINION", "GRAMS", "HORNBERGER", "VANCAMP", "DEWALD", "RIVES", "SANKEY", "KLEINMAN", "FALCONER", "RUMPH", "DEPASQUALE", "GAMINO", "MATUS", "OLMSTED", "SPINNER", "SWETT", "ABSHER", "CULLER", "FRYMAN", "CARLYLE", "LAMPERT", "CHOUINARD", "DUNAGAN", "TERRANOVA", "WESOLOWSKI", "HETHERINGTON", "SCALISE", "JOUBERT", "MARCANO", "PENDERGAST", "SCHELLER", "LENOIR", "WHISENHUNT", "MAHAR", "PECORARO", "VANLANDINGHAM", "YOU", "DAUM", "EDDINGTON", "NATIVIDAD", "PENICK", "DELEO", "SANTUCCI", "SOLTIS", "COSTANZA", "FARLOW", "HINER", "DUPREY", "FANN", "HARTSOCK", "SAFFORD", "MURTHA", "CHIEN", "DEVERA", "FESSLER", "PAYNTER", "BOLTZ", "HOELSCHER", "DEACON", "LOO", "DILORENZO", "ENOCH", "MIRZA", "SAVILLE", "TAKACS", "DREXLER", "LAKIN", "ESTEVES", "GERAGHTY", "LLANES", "WIDMER", "CERNY", "HARGRAVES", "QUIST", "ALDERETE", "CHAPPLE", "TARTER", "TOMA", "BATEY", "CLYMER", "MICHELSON", "SEALEY", "COURVILLE", "DESOUSA", "LOUGHLIN", "PREECE", "ZURITA", "NOLES", "SHAMBLIN", "TINGLEY", "MISNER", "STANDIFER", "DINARDO", "DILLOW", "BULLIS", "CARBALLO", "EVERLY", "CARLE", "MULVIHILL", "TINCHER", "BIRDSALL", "LUNDIN", "BAINBRIDGE", "SUTTLE", "WIGHTMAN", "BICKHAM", "MOUNTAIN", "MOWER", "DURANTE", "MCGRUDER", "SWINFORD", "VIVEROS", "GRABLE", "GWYNN", "TAPLEY", "WIEBE", "DASH", "STAGG", "CLUFF", "HEITMAN", "FORTUNA", "HUERTAS", "LINES", "SLY", "HALFORD", "HELSEL", "BICKNELL", "BLAKEMAN", "COLANGELO", "OLNEY", "QUINTON", "ROTHROCK", "HONE", "PREJEAN", "RENZ", "FITZHUGH", "LATOUR", "NEWBOLD", "OSHIRO", "SERIO", "SONGER", "CARDIN", "GETER", "ABBAS", "BARBERA", "BLAKESLEE", "CAESAR", "CAMPER", "CANCEL", "DONELSON", "DRISKILL", "MCCLURG", "BORRELLI", "DONOGHUE", "SHOAF", "TINAJERO", "ARZATE", "KEESEE", "PASLEY", "STRODE", "ACKERSON", "BROCKINGTON", "JOWERS", "MORELLO", "TRANTHAM", "BARCIA", "DINGER", "LIPP", "RIDINGS", "CANAVAN", "HAGANS", "RANK", "BECKMANN", "LAMPLEY", "BJORK", "RAYGOZA", "SCHIRMER", "LONGMIRE", "SCHIAVONE", "BREUER", "LORE", "STENSON", "CALE", "CHANNELL", "CULBERSON", "KOZIOL", "TRADER", "MUNDT", "NEMEC", "SICKLES", "HOLL", "STRIBLING", "BERENS", "DEEM", "LEHNER", "NAUMAN", "BILLMAN", "CASTELLI", "DAVY", "GUMM", "ORNDORFF", "PELHAM", "SPOTTS", "JURGENS", "SWORD", "ADORNO", "BOUGHTON", "GORRELL", "BOBADILLA", "MAUER", "MOLINE", "GUAY", "BARANOWSKI", "GUTIERRES", "HOLSINGER", "BEVERIDGE", "MARABLE", "BERKEY", "LAMOTHE", "SPITLER", "CARBAUGH", "HOOPES", "MILFORD", "WILKEN", "BINGAMAN", "CRIPPEN", "OMAN", "SHOCK", "YARNELL", "KOST", "WETHINGTON", "BIRNBAUM", "EUGENE", "FORAN", "GAUDETTE", "SPIELMAN", "STARKE", "DOCTOR", "HEDGEPETH", "HIGUERA", "HUSSEIN", "NAVARRETTE", "RANSON", "BROUGH", "COOKSON", "GOWEN", "MENDONCA", "PROVENCHER", "RUTZ", "SUMMER", "READER", "DOUD", "RAVEN", "BITTLE", "GUNNING", "PEACHEY", "TORIBIO", "VALE", "AKER", "DAMORE", "HARNISH", "MARANO", "BULGER", "PASILLAS", "THROCKMORTON", "UTZ", "VANZANT", "CORPUS", "HOLMGREN", "LONGLEY", "CARSTENS", "LINE", "PERCIVAL", "WETMORE", "AYOTTE", "BATRES", "PIPES", "ALPERT", "LUDWICK", "PICK", "CARLOCK", "EDMUNDSON", "FEINSTEIN", "DAHLGREN", "KROUSE", "SASAKI", "LIEB", "LONDONO", "OLOUGHLIN", "WARDLAW", "CASTELLO", "LINEBERRY", "MILSTEAD", "PARE", "PARMENTER", "RIFFE", "SITTON", "CALABRO", "DELCASTILLO", "MANOR", "TARIN", "BOAZ", "CELESTINE", "CHAMBLEE", "COCO", "ELKIN", "GRILL", "NICK", "MEEKINS", "MOISE", "STORK", "DEVERS", "JUN", "BRICK", "KEGLEY", "BIGGERSTAFF", "KERSTEN", "LOBATO", "JAYNE", "NASSER", "SOUTHALL", "EADDY", "KEMPTON", "PALADINO", "BERARDI", "PIZZO", "CRANSTON", "FROMM", "OHALLORAN", "PULVER", "ROWDEN", "CAPOBIANCO", "GALLION", "HOUSEMAN", "KAHLE", "MALOTT", "MAUL", "THIESSEN", "PAULY", "PELLERIN", "TRESSLER", "CRYER", "FIRTH", "JEANLOUIS", "SAINZ", "CHRONISTER", "HAYASHI", "MONG", "POSNER", "TRAWICK", "CUEVA", "SHERWIN", "GORDEN", "LACASSE", "BOHL", "COAN", "HOCKER", "TWIGG", "GOODALE", "LOEB", "PERRAULT", "URBANO", "CARCAMO", "FRAWLEY", "RICHBURG", "HENNINGS", "MOFFAT", "WEYER", "MYATT", "TUNNELL", "ULLMAN", "HERN", "LOPRESTI", "JAGGERS", "KNISLEY", "SONNENBERG", "TANKSLEY", "TWOMEY", "POPPE", "RACHAL", "KANIA", "KYSER", "MILLSAPS", "PATTY", "PEIRCE", "POUND", "ROMER", "SPEAKMAN", "VOS", "TELFORD", "HEGARTY", "KELLETT", "MICHAELIS", "HALLIGAN", "HERB", "MAUGHAN", "RAINER", "ROBICHAUD", "BLOM", "FISCUS", "LAVINE", "SICKLER", "MEDEL", "BOLYARD", "CREEKMORE", "HASKIN", "LALIBERTE", "MAGRUDER", "SECOR", "BERNABE", "CAVIN", "DRAGO", "LEADER", "LUKENS", "VASSALLO", "PLETCHER", "EDINGTON", "FUSON", "HASSON", "HUCKABEE", "EICHLER", "HERING", "VONG", "MARDIS", "GU", "BILYEU", "DUNTON", "FRAGOSO", "GAMA", "RUNION", "SEGARRA", "CRUMPLER", "FRADY", "LEWELLEN", "FURLOW", "JESKE", "DELAPENA", "HAMLET", "KALE", "MASSENGALE", "GALLI", "ESTEBAN", "GREESON", "SHUE", "MAITLAND", "PINNEY", "POLLAK", "RUFFNER", "STEVEN", "FRAIRE", "HOCKETT", "ELBERT", "HOGGARD", "LABARGE", "MULHERN", "SILCOX", "SAEZ", "DARLINGTON", "MCCARROLL", "PALAZZO", "PILLOW", "SLUDER", "STAMP", "BLAHA", "DEMARIA", "SWANGER", "WINNINGHAM", "LIPPINCOTT", "DAKE", "GOLDSBERRY", "MURAWSKI", "SEIDL", "WOOLFOLK", "HOBART", "KIMBER", "NILSSON", "STOUGH", "ALMENDAREZ", "NEVELS", "DENMARK", "FASANO", "LATHAN", "MOSELY", "SALMONS", "STENGEL", "DROWN", "FELICE", "MENDIETA", "CALLIHAN", "HOWZE", "POLSTON", "VIDRINE", "EAKINS", "FEATHERSTONE", "LEEK", "ASUNCION", "ATHEY", "LAJOIE", "ASHBAUGH", "MORRISSETTE", "ORMAN", "PEART", "HAMNER", "DIETER", "DRY", "TERRONES", "ZELL", "BAKKER", "BANISTER", "CAMPUZANO", "REVELES", "ARCEO", "DHILLON", "GINSBURG", "GO", "NORMAND", "RUBINSTEIN", "SHAVERS", "ARENS", "CISCO", "CLUTTER", "HACKLER", "JAQUES", "TRAXLER", "CERON", "GILLENWATER", "OTTINGER", "STARRETT", "BLAKEMORE", "CASTER", "THORSEN", "BAUR", "HALDEMAN", "HOWER", "MOLINAR", "MCALPIN", "OLIVERI", "BENGTSON", "STANDISH", "BARNA", "BLACKSTOCK", "CORDOBA", "SCHANTZ", "STRACK", "BREESE", "HAWKINSON", "SABA", "CAMDEN", "GWALTNEY", "CORLISS", "CRUISE", "DUGGINS", "MCNEESE", "SMIT", "BURMAN", "LAUB", "KENWORTHY", "NUTTALL", "SANTINI", "SHABAZZ", "SPOHN", "STJEAN", "WILLISON", "GERRY", "KOEPKE", "MANES", "MCLAMB", "OGBURN", "REESER", "BREWTON", "CARRERO", "LIVERMORE", "RISINGER", "WEGENER", "HARSH", "LECOMPTE", "UTTERBACK", "BAPTISTA", "FOSHEE", "GRAVELY", "HONEA", "SCHNABEL", "STRYKER", "TING", "COURSON", "GOYETTE", "LAURENCE", "LEITCH", "RENEAU", "TASKER", "RANGE", "TILSON", "VOIGHT", "BOICE", "DUFRENE", "HALLAM", "LENARD", "SHREWSBURY", "SISTRUNK", "STURGES", "WEITZ", "CALLEN", "CARNEVALE", "HEPNER", "OSHAUGHNESSY", "WEHNER", "MOUSER", "WINGERT", "PALMORE", "ALCAZAR", "ELIA", "RUGG", "AVITIA", "PENTON", "BRISCO", "AMBROSIO", "WARDLOW", "BUGGS", "DITTMER", "LEAF", "ROWLES", "SCHWEIZER", "PULEO", "CARDINALE", "HAUGHTON", "VADEN", "MINARD", "RUDDY", "SEGUIN", "STALKER", "BENNINGTON", "BROADUS", "HILT", "WORKS", "BUSTER", "ENGELS", "HADDIX", "BOPP", "RECKER", "WILTON", "BOOTS", "COSTANTINO", "FALKNER", "MCGARY", "TENNISON", "HOLZ", "LOFGREN", "PUTNEY", "CHRISTNER", "FRUGE", "VASSAR", "PEARLMAN", "SPOON", "VANKIRK", "GUERTIN", "MEECE", "PETTERSON", "SARTAIN", "CARDILLO", "PRIMM", "DRYER", "CHAISSON", "DANE", "HARTSHORN", "CREAGER", "DISALVO", "ESPITIA", "JANIK", "PARENTE", "KUJAWA", "PAIVA", "SLAVEN", "TAGUE", "FOOR", "FRAMPTON", "GRUVER", "PROKOP", "COLLIS", "LAMKIN", "METTLER", "COLYER", "MASI", "SHUEY", "TEPPER", "GUICE", "HURWITZ", "TRUMBLE", "MCCULLY", "WINDLE", "CUTTING", "GRULLON", "MORFIN", "STOTLER", "WAGSTAFF", "DEHAAN", "NOON", "FLESHER", "ALBAUGH", "COLL", "COVELL", "FERRI", "LUCY", "GORDILLO", "TESTERMAN", "BRINKERHOFF", "BROCKETT", "CALLE", "CHUMLEY", "CROWL", "JEPSON", "MCELWAIN", "GARZON", "POLAK", "REVELL", "ROTHENBERG", "SOCHA", "THOMS", "FELTY", "PEGUERO", "PING", "TSO", "VALLEJOS", "CHARLESTON", "FEDOR", "HAIDER", "ABE", "ENLOW", "FIFER", "BUMPUS", "KEELE", "MCDAVID", "PANEK", "DYESS", "SCHOLTEN", "CORRY", "DONOHOE", "GRIFFEY", "HEATHERLY", "HOBAN", "MCCLEAN", "ADKISON", "FEATHERS", "KILLEEN", "PLYLER", "FIORENTINO", "HOEFT", "MCBETH", "MYHRE", "ERAZO", "FULBRIGHT", "MADSON", "WILDS", "MCGAUGHEY", "MONTEITH", "MURGUIA", "PETRUCCI", "HAUSMAN", "BRISSON", "LAIN", "RUNKLE", "SHUTE", "ZUKOWSKI", "CAFFREY", "ELSON", "HICKOK", "MILLION", "PEAY", "HAGA", "ANCHETA", "BLAS", "CARMEN", "CORDLE", "PETTIFORD", "BACKMAN", "DIMARTINO", "MOZINGO", "SPAHR", "KONRAD", "STGEORGE", "BUHLER", "MCELRATH", "OLIVEROS", "EDELSTEIN", "CADET", "GILMARTIN", "MUNDAY", "ROANE", "DESALVO", "LEPE", "LINKOUS", "SHEARIN", "SYMONS", "CHESHIRE", "BEAGLE", "DEWALT", "ESCH", "KLEMM", "POOLER"}

std::string	Zombie::randomName( void ) {
	const	std::string		save[] = NAMES;
	const	size_t			len = sizeof(save) / sizeof(save[0]);
	static	size_t			limit = len;
	static	std::string 	pool[] = NAMES;
	size_t					i = len;
	std::string				str;
	size_t					pos;

	while (i != 0)
	{
		pos = rand() % len;
		str = pool[pos];
		if (!str.empty())
		{
			str[0] = std::toupper( str[0] );
			i = 1;
			while (i < str.length()) {
				str[i] = std::tolower( str[i] );
				++i;
			}

			pool[pos].clear();
			--limit;
			if (limit == 0) {
				i = 0;
				while (i < len) {
					if (pool[i].empty())
						pool[i] = save[i];
					++i;
				}
				limit = len / 10;
			}
			return (str);
		}
		--i;
	}
	return ("Unknown");
}

Zombie::Zombie( void ) {
	this->name = Zombie::randomName();
	this->type = "Unknown";
}

Zombie::Zombie( std::string name, std::string type ) {
	this->name = name;
	this->type = type;
}

Zombie::~Zombie( void ) {
}

void	Zombie::announce( void ) const {
	std::cout << "<" << this->name << " (" << this->type << ")> Braiiiiiiinnnssss..." << std::endl;
}
